spring:
  config:
    import: optional:file:.env[.properties]
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: ${DB_URL}
    driverClassName: org.h2.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
  liquibase:
    change-log: classpath:db/db.changelog-master.yaml
    enabled: true
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${OAUTH2_CLIENT_ID}
            client-secret: ${OAUTH2_CLIENT_SECRET}
            redirect-uri: "http://16.171.35.45:8080/login/oauth2/code/google"
            scope:
              - email
              - profile
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/v2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
      resourceserver:
        jwt:
          issuer-uri: ${ISSUER_URI}

  graphql:
    cors:
      allowed-origins: ${ALLOWED_ORIGINS}

custom:
  api:
    paths:
      v1: /api/v1
  auth:
    jwt:
      secret: ${JWT_SECRET}
      expiration: ${JWT_EXPIRATION}